name: conversator
description: With the conversator, you can send data/message across files. It works like web socket but it runs locally.
version: 1.0.1
homepage: https://github.com/ragokan/conversator-dart
repository: https://github.com/ragokan/conversator-dart

environment:
  sdk: '>=2.10.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
